### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlencode'

### ISSUE THREAD

**Issue by ghost** [thetvdb/tvdb-v4-python#13]
Hi , 

Is it this my fault or what ?
Thanks so much

`
import tvdb_v4_official
tvdb = tvdb_v4_official.TVDB('...')
series = tvdb.search('White Collar - Fascino criminale')
print(series)

AttributeError: module 'urllib' has no attribute 'urlencode'

`

**Comment by vissieGP** [comment]
urllib has been split up in Python 3.
The urllib.urlencode() function is now urllib.parse.urlencode(),
the urllib.urlopen() function is now urllib.request.urlopen().

I changed my line 159 from
qs = urllib.urlencode(filters)                                                                                                                                                                                                       
to
qs = urllib.parse.urlencode(filters)

That fixed that one error. Still playing to get my head around this code.
