### ISSUE TITLE
get_episodes_translation() only partially implemented

### ISSUE THREAD

**Issue by mmayer** [thetvdb/tvdb-v4-python#15]
It was suggested to me I open a ticket here after creating a support ticket on thetvdb.com.

I noticed today that the method get_episodes_translation() exists in tvdb_v4_official.py, but there are two problems with it.

1. The method only takes a language argument, but it passes language and id to episode_translation_url(). Naturally, id is an unknown variable at that point.
2. The method episode_translation_url() doesn't even exist.

I do have a fix for this, which I can push to my clone, if there is any interest. The fix is working for me.

**Comment by antheaezzell** [comment]
@mmayer we are testing a solution and will get back to you, but your request has been ticketed.

A ticket for our internal reference - https://mediamorph.atlassian.net/browse/TVD-2699

**Comment by antheaezzell** [comment]
@mmayer this was recently released, please let me know if you continue to experience any issues.
