### ISSUE TITLE
Pagination is not fully supported

### ISSUE THREAD

**Issue by almightiest** [thetvdb/tvdb-v4-python#18]
For a method such as `get_series_episodes` that takes in a `page` parameter, I would expect pagination data to be returned for navigating through any of the pages beyond the initial page 0.  If I make a request for The Simpsons (id 71663) without a page, I get 500 results (page 0), but there are 781 total results available across 2 pages.  There is no way of knowing that in the `data` response alone, since `links` information is missing from the response.

Initial request: `https://api4.thetvdb.com/v4/series/71663/episodes/default/eng`

Result model:
- status
- data (this is all that is returned from the `get_series_episodes` method return)
- links (this indicates there is a `next` page to get the remaining 281 results from the initial 500, but is unavailable)

I cannot programmatically determine that there are more results.

**Comment by antheaezzell** [comment]
@pgjensen this issue has been ticketed to our developer. 

Internal ticket for our reference - https://mediamorph.atlassian.net/browse/TVD-2746

**Comment by antheaezzell** [comment]
@pgjensen this issue was resolved in v1.0.2 but please let me know if you are continuing to see an issue.
