### ISSUE TITLE
Print statement (debug) in main code for get_series_extended

### ISSUE THREAD

**Issue by almightiest** [thetvdb/tvdb-v4-python#29]
https://github.com/thetvdb/tvdb-v4-python/blob/ba7184ecbce4f1d543101af0c0cc7421219559bb/tvdb_v4_official.py#L174

This should be removed.

**Comment by antheaezzell** [comment]
Ticketed for the Python client. I will discuss with the developers and get back to you @almightiest .

See internal ticket for our reference - https://mediamorph.atlassian.net/browse/TVD-3122

**Comment by antheaezzell** [comment]
@almightiest this was also released today.
