### ISSUE TITLE
Missing method for /series/{id}/artworks

### ISSUE THREAD

**Issue by almightiest** [thetvdb/tvdb-v4-python#30]
There isn't a `get_series_artworks` method per the spec here: https://thetvdb.github.io/v4-api/#/Series/getSeriesArtworks

https://github.com/thetvdb/tvdb-v4-python/blob/main/tvdb_v4_official.py#L186 is the area I'd expect to see it in.

**Comment by antheaezzell** [comment]
We will discuss this internally @almightiest and I will get back to you.

Internal ticket for our reference - https://mediamorph.atlassian.net/browse/TVD-3124

**Comment by antheaezzell** [comment]
@almightiest this was released today. See release notes.
