### ISSUE TITLE
Implement v4.6.5 API feature for If-Modified-Since header

### ISSUE THREAD

**Issue by almightiest** [thetvdb/tvdb-v4-python#32]
Support for [If-Modified-Since #110](https://github.com/thetvdb/v4-api/issues/110) would be nice to have in the tvdb-v4-python library!  It would help reduce unnecessary orchestration and web traffic through a simple header parameter.

It'd be nice if it supported (or was compatible with) the python requests and [requests-cache](https://requests-cache.readthedocs.io/en/stable/user_guide/headers.html) libraries.  https://httpcache.readthedocs.io/en/latest/

**Comment by antheaezzell** [comment]
This has already been ticketed @almightiest internal ticket for our reference - https://mediamorph.atlassian.net/browse/TVD-3152

**Comment by antheaezzell** [comment]
@almightiest included in today's release. Let me know if you have any questions.
