### ISSUE TITLE
APIKey problem

### ISSUE THREAD

**Issue by AdamMoses-GitHub** [thetvdb/tvdb-v4-python#34]
I execute the example code using the APIKEY and PIN provided from the TVDB dashboard, and yet it fails.

Is there another step required?

> Exception: Code:HTTP Error 401: Unauthorized, InvalidAPIKey: apikey invalid

**Comment by antheaezzell** [comment]
@AdamMoses-GitHub let us have a look and we will get back to you. Internal ticket for our reference:

https://mediamorph.atlassian.net/browse/TVD-3238

**Comment by maxifwortman** [comment]
@AdamMoses-GitHub be sure to use the code correctly and download the tvdb_v4_official pyhton package.
Here is a code sample:

```python import tvdb_v4_official
tvdb = tvdb_v4_official.TVDB("f0911b88-22bc-4daf-937a-3c843b55ca21", pin="GHJP5BN")

series = tvdb.get_series(70366)
print(series)
```

Let us know if you continue to see any issues.

**Comment by antheaezzell** [comment]
I'm closing this issue for now @AdamMoses-GitHub but let us know if you continue to experience any problems.
