### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by AdamMoses-GitHub** [thetvdb/tvdb-v4-python#40]
I am subscriber and therefore have an active legacy API key and PIN, this can't be used on the v4 API, is that correct?

So I need a different API key for v4?

Is there any support still for the legacy API? The website seems to indicate different dates for when it will expire.

**Comment by antheaezzell** [comment]
That is right. The legacy key + PIN will only work on the older APIs. We do not have a firm sunset date on the legacy APIs, but it will happen this year. There's unfortunately, no support available for the legacy APIs and we are strongly encouraging our developer community not to begin development against them at this time.

**Comment by AdamMoses-GitHub** [comment]
So to be clear then, there is no support for the legacy API and just being a regular subscriber does not grant me a V4 API key, so effectively I can't use the API at all?

**Comment by antheaezzell** [comment]
If you want a developer's key to explore the v4 API or want to apply for a commercial key to the v4 API, you'll need to apply for one and we will approve it with conditions. If this is a personal project, you can feel free to apply for a v4 key for free via our [Earn Points](https://thetvdb.com/points) feature. All of this can be done through your dashboard.

**Comment by antheaezzell** [comment]
I'm going to close out this ticket @AdamMoses-GitHub but please let us know if you need anything further.
