### ISSUE TITLE
Unauthorized access

### ISSUE THREAD

**Issue by james-berkheimer** [thetvdb/tvdb-v4-python#42]
Hi I subscribed on the website to get a legacy key and a pin.  But when I try to use the Python API I get an unauthorized access.  Not sure where else to turn for support since I can't get access to the actual TVDB support page.

**Comment by antheaezzell** [comment]
The legacy key access most likely will not work for the python client because the python client is working off of the new (v4 API) which is why I think you are getting an unauthorized error. If you intend to make use of the python client for a new project, I would suggest you make a v4 API key via your dashboard on the site. If it's for a commercial project, I would suggest selecting that funding model and it will go into a queue for business review. If it's for personal use you can earn a free subscription by working in our Earn Points feature [here](https://thetvdb.com/points) or choosing to subscribe. Hope that helps.

**Comment by james-berkheimer** [comment]
Hi thanks for the reply.  Yes, this is for personal use and I already paid for a subscription to gain access to the API python module.  So my question is, does the subscription not pay for access to this module?

**Comment by szsori** [comment]
You should create a new v4 API key that's set as the subscription model (it's an option when creating it).  And then use the PIN provided by subscribing.  The legacy API keys are only for the legacy API.

**Comment by james-berkheimer** [comment]
OK so I followed those steps for creating the v4 API key and gave it my pin.  I have a key but when I tried using it, I got another error.

```
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvdb_v4_official.py", line 18, in __init__
    with urllib.request.urlopen(req, data=loginInfoBytes) as response:
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/James/Code/python/tvdb/tvdb.py", line 3, in <module>
    tvdb = tvdb_v4_official.TVDB("APIKEY")
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvdb_v4_official.py", line 84, in __init__
    self.auth = Auth(login_url, apikey, pin)
  File "C:\Users\James\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvdb_v4_official.py", line 23, in __init__
    raise Exception("Code:{}, {}".format(e,res['message']))
Exception: Code:HTTP Error 400: Bad Request, Bad Request
```

**Comment by szsori** [comment]
Hi James.  It looks like you're using this call:
`tvdb = tvdb_v4_official.TVDB("APIKEY")`

Use this one instead:
`tvdb = tvdb_v4_official.TVDB("APIKEY", pin="YOUR PIN HERE")`

Also, your API key is in your traceback... you should edit that out.

**Comment by james-berkheimer** [comment]
OK that worked, thanks!  So after I created the v4 API key my pin disappeared from my account page.  I had to find it on the "subscription" tab of my account page.

Also, thanks for pointing out the API key exposure.  I fixed that.

**Comment by darthShadow** [comment]
You may want to invalidate the API Key itself. It's still there in your post edit history for those who want to grab it.

**Comment by james-berkheimer** [comment]
Ok, how exactly do I go about doing that?  I don't see any obvious way on the API keys tab.

**Comment by darthShadow** [comment]
Probably best to reach out to support.

**Comment by szsori** [comment]
@james-berkheimer Please make a support ticket here: https://support.thetvdb.com/.  Include your current key and say that it should be deleted.  Then create a new key and start using that.  I'll remove the old key once I see that ticket.  Can't do it now since you correctly edited your comment.  And thank you @darthShadow .

**Comment by szsori** [comment]
@james-berkheimer I've just removed your old key.  Go ahead and create a new one in the same way.  And thank you, @darthShadow .  Good point.

**Comment by james-berkheimer** [comment]
Ticket created.  Thanks everyone.
