### ISSUE TITLE
There is a "print" command in function "get_series_extended"

### ISSUE THREAD

**Issue by advorsky73** [thetvdb/tvdb-v4-python#5]
There is a "print" in function "get_series_extended".  
This cannot be intended I guess?

**Comment by advorsky73** [comment]
Yes / No / Maybe / We will remove it / We will keep it ?????

**Comment by WayneD** [comment]
Note that the latest master branch has removed the print.

**Comment by advorsky73** [comment]
Whoever did that, has no clue what to do with the issues section here, no? 🤦 
Thanks @WayneD !
