### ISSUE TITLE
Key error on tvdb.get_series_extended(82298)["episodes"]

### ISSUE THREAD

**Issue by advorsky73** [thetvdb/tvdb-v4-python#6]
Here is the output from my script:
https://api4.thetvdb.com/v4/series/82298/extended  (<- THAT is btw the print in get_series_extended :( )
Traceback (most recent call last):
  File "C:\temp\listme.py", line 67, in <module>
    meps = getMissingEpisodes(directory)
  File "C:\temp\listme.py", line 48, in getMissingEpisodes
    tvdblist = getTVDBList(seriesId, ignoreSpecials)
  File "C:\temp\listme.py", line 23, in getTVDBList
    eps = tvdb.get_series_extended(seriesId)["episodes"]
KeyError: 'episodes'

**Comment by advorsky73** [comment]
The same exception is thrown as well for these ids:
* 82486
* 336688
after that I stopped testing...

**Comment by WayneD** [comment]
It appears that the episodes information for a get_series_extended() result is not guaranteed to exist (I'm not sure why it exists at all, really). You can still get all the episodes by querying the seasons:

```python
    series = tvdb.get_series_extended(82298)
    if 'episodes' not in series or not series['episodes']:
        series['episodes'] = [ ]
        for season in sorted(series["seasons"], key=lambda x: (x['name'], x['number'])):
            if season['name'] == 'Aired Order': # or: if season['type']['type'] == 'official':
                season = tvdb.get_season_extended(season['id'])
                series['episodes'] += season['episodes']
```
This is also an example of how you can override the episodes with those from an alterate order.

**Comment by advorsky73** [comment]
of course there is a workaround, but this results in a lot of queries, instead of one, which makes the call pretty useless.
I really would prefer to have this fixed on the tvdb side... ;)

**Comment by WayneD** [comment]
I'd imagine that are not going to be returning all episodes in the series request going forward, so I wouldn't expect it. It's too much data for many series.

It looks like the API supports both a per-season request and a paged request for all episodes (the latter with 500 episodes at a time). Sadly, the latter is missing from the python lib.  I've included it in my merge request from https://github.com/WayneD/tvdb-v4-python

For typical shows (which generally have small seasons) a use of that added `tvdb.get_series_episodes(sid)` call would return all the episodes (since most shows have less than 500) so no extra pages would need to be requested.

**Comment by advorsky73** [comment]
I checked and most of the requests failing as described above do NOT belong to series with a lot of episodes.
e.g. 82298 has 39 episodes and does not work, whereas 73141 has over 300 episodes and does work.
There must be something other to it....

**Comment by WayneD** [comment]
Yeah, that is indeed weird. Hopefully someone in-the-know can enlighten us.

**Comment by advorsky73** [comment]
Apparently there is not much interest in solving this :(

**Comment by waggertron** [comment]
@advorsky73 we will be looking into this issue on the tvdb side, thank you for bringing it to our attention.

**Comment by advorsky73** [comment]
Thanks @waggertron for the update ! At least I know now this issue was seen by the tvdb team ;)

**Comment by antheaezzell** [comment]
@advorsky73 I do apologize that this issue has gotten overlooked. I have spoken with our lead developer and he believes he knows of a solution for the problem. It should be addressed in the next upcoming sprint. Again, my apologies on the delayed.

Here is our internal ticket for our reference - https://mediamorph.atlassian.net/browse/TVD-2676

**Comment by antheaezzell** [comment]
@advorsky73 I apologize for the length of time it has taken for us to address this issue, but it was recently released. Please let me know if you are still experiencing any issues.
